sudo: false
language: java
jdk:
  - oraclejdk8
env:
  global:
    - PATH=$PATH:${HOME}/google-cloud-sdk/bin
before_install:
  - bin/install_gcloud_sdk
  - bin/start_datastore_emulator
script: 
  - bin/run_tests
